blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as aviews


from . import views as bv

urlpatterns = [
    url(r'^$', bv.index, name='index'),
    url(r'^demo/$', bv.demo),
    # url(r'^some/$', "blog.views.some"),
    url(r'^new/$', bv.create_post, name='new'),
    # url(r'^(?P<id>\d{1,2})/$', bv.detail, name='detail'),
    # url(r'^(?P<id>\d{1,2})/edit/$', bv.update, name='edit'),
    # url(r'^(?P<id>\d{1,2})/del/$', bv.delete, name='delete'),

    url(r'^(?P<slug>[\w-]+)/$', bv.detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', bv.update, name='edit'),
    url(r'^(?P<slug>[\w-]+)/del/$', bv.delete, name='delete'),




]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as aviews
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', aviews.login, name='login'),
    url(r'^logout/$', aviews.logout, name='logout'),
    url(r'^com/', include("comments.urls", namespace='comments')),
    url(r'^b/', include("blog.urls", namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.conf import settings
from django.contrib.contenttypes.models import ContentType


from markdown_deux import markdown

from comments.models import Comment


def upload_location(instance, filename):
    return "{}/{}".format(instance.title, filename)


class PostManager(models.Manager):

    def all(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)#('auth.User')
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    # image = models.FileField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True, blank=True,
                              width_field='width_field',
                              height_field='height_field')
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    text = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    created_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    """
    you're going to allow a field to be blank in your form,
    you're going to also need your database to allow NULL values for that field.
    The exception is CharFields and TextFields, which in Django are never saved as NULL.
    Blank values are stored in the DB as an empty string ('').
    """

    objects = PostManager()

    # def publish(self):
    #     self.published_date = timezone.now()
    #     self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    def get_markdown(self):
        text = self.text
        return mark_safe(markdown(text))

    class Meta:
        ordering = ['-created_date', 'title', ]

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

blog/forms.py
from django import forms
from .models import Post

from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
    text = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget())
    class Meta:
        model = Post
        fields = [
            'title',
            'text',
            'author',
            'image',
            'draft',
            'publish',
        ]

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote_plus
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType

from comments.forms import CommentForm
from .models import Post
from .forms import PostForm
from comments.models import Comment

def s(request):
    return HttpResponse("<h1>Hello</h1>")

def demo(request):
    return render(request, 'demo_static.html')

def some(rq):
    return HttpResponse("<h2>Some text here</h2>")

def index(rqst):
    post_list = Post.objects.all().order_by('-created_date')
    page = rqst.GET.get('page')
    query = rqst.GET.get('qry')
    if query:
        post_list = post_list.filter(
            Q(title__icontains=query) |
            Q(text__icontains=query) |
            Q(author__first_name__icontains=query) |
            Q(author__last_name__icontains=query)
        )
    paginator = Paginator(post_list, 6) # Show 8 contacts per page
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:  # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:  # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(rqst, 'blog/index.html', {'objects': posts, 'user':rqst.user})


def detail(request, slug=None):
    # object = Post.objects.get(id=id)
    object = get_object_or_404(Post, slug=slug)
    share_string = quote_plus(object.text)

    initial_data = {
        'content_type': object.get_content_type,
        'object_id': object.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        print(form.cleaned_data) # sends CommentForm fields as dictionary
        c_type = form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        c_data = form.cleaned_data.get('content')

        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()


        new_comment, created = Comment.objects.get_or_create(
            author=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=c_data,
            parent=parent_obj,

        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = object.comments # = (def @prop) Comment.objects. filter_by_instance(object)

    return render(request, 'blog/detail.html', {'obj': object,
                                                'share_string': share_string,
                                                'comments': comments,
                                                'comment_form': form,
                                                })

def create_post(rqst):
    if not rqst.user.is_staff and not rqst.user.is_superuser:
        raise Http404
    form = PostForm(rqst.POST or None, rqst.FILES or None)
    context = {
        'form': form
    }
    if form.is_valid():
        inst = form.save(commit=False)
        inst.user = rqst.user
        inst.save()
        messages.success(rqst, 'Succesfully created! Congratulations!')
        return HttpResponseRedirect(inst.get_absolute_url())
    return render(rqst, 'blog/postform.html', context)

def update(request, slug):
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        inst = form.save(commit=False)
        inst.save()
        messages.success(request, 'Succesfully changed! Congratulations!')
        return HttpResponseRedirect(instance.get_absolute_url())
    # else:
    #     messages.error(request, "Unfortunately entry couldn't be changed")
    context = {
        'title': instance.title,
        'instance': instance,
        'form': form
    }
    return render(request, 'blog/postform.html', context)

def delete(request, slug):
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, 'Succesfully deleted')
    return redirect("posts:index")

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Title {% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>


<!-- Optional theme -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">-->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
<link rel="stylesheet" type='text/css' href="{% static 'newstyle.css' %}"/>

<style>
    {% block style %} {% endblock style %}
</style>

{% block head_extra %}
{% endblock head_extra %}


</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container">
<p><a href="{% url 'posts:new' %}" class="btn btn-info" role="button">New post</a>
<a href="{% url 'posts:index' %}" class="btn btn-success" role="button">Index</a></p>
</div>
<hr>

{% include "blog/messages.html" %}

{% block content %}
{% endblock content %}
<!-- Latest compiled and minified JavaScript -->

<script
  src="http://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

<script type="text/javascript" src="{% static 'my.js' %}"></script>
</body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block title %} Object details {% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-4">
  <h1>{{ obj.title }}</h1>
  <h3>
    {% if obj.author.get_full_name %}
    {{ obj.author.get_full_name }}
    {% else %}
    {{ obj.author }}
    {% endif %} </h3>

  <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/"
       data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

  <img src="{{ obj.image.url }}" class="img-responsive" style="max-height:600px">


  <p style="font-style: italic">{{ obj.publish }}</p>
  {% if obj.draft %}
  <p style="color: red">Draft</p>
  {% endif %}
  <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
    Facebook
  </a>

  <a href="https://twitter.com/home?status={{ obj.text|urlify }}%20{{ request.build_absolute_uri }}">
    Twitter
  </a>

  <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google+</a>

  <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}
        &title={{ obj.title }}&summary={{ share_string }}&source=http://swiftforentrepreneurs.com/">
    Linkedin</a>

  <div class='row'>
    <div class='col-sm-12'>
      <div class="post-detail-item">
        <h2>{{ obj.get_markdown }}</h2>
      </div>

      <div>
        <p class="lead">Comments</p>
        <form method="POST" action="."> {% csrf_token %}
          {{ comment_form|crispy}}
          <input type="submit" value="Comment" class="btn btn-default ">
        </form>

        {% for comment in comments %}
        <blockquote>
          <p>{{ comment.content }}</p>
          <footer>{{ comment.author.get_full_name }}, <cite title="Source Title">{{ comment.timestamp }}</cite>
            {% if comment.children.count > 0 %}
            | {{ comment.children.count }} comments
            |<a class="comment-reply-btn" href="#"> Reply</a>
            {% endif %}
          </footer>

          <div class="comment-reply">
            {% for child_comment in comment.children %}
              <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>{{ child_comment.author.get_full_name }}, <cite title="Source Title">{{ child_comment.timestamp }}</cite></footer>
              </blockquote>
            {% endfor %}
            <form method="POST" action="."> {% csrf_token %}
              {{ comment_form|crispy}}
              <input type="hidden" name="parent_id" value="{{ comment.id }}">
              <input type="submit" value="Reply" class="btn btn-default ">
            </form>
          </div>


        </blockquote>
        {% endfor %}
      </div>

    </div>
  </div>
  <a href="{% url 'posts:edit' slug=obj.slug %}" class="btn btn-warning" role="button">Edit</a>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block title %} Index {% endblock %}

{% block content %}
<div class="col-sm-offset-4 col-sm-4 col-sm-offset-4">
    <div>
        <h5>Logged user: {{user}} authorized: {{user.is_staff}}</h5>
    </div>

    <form class=row method="GET" action="">
        <div class="col-sm-8">
            <div class="input-group">
                <input class="form-control" type="text" name="qry" value="{{ request.GET.qry }}" placeholder="search..."/>
                <span class="input-group-btn">
                    <!--<input class="btn btn-default" type="submit" value="SEARCH!"/>-->
                    <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>
                </span>
            </div>
        </div>
    </form>
{% for obj in objects %}
<div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">
            {% if obj.image %}
            <img src="{{ obj.image.url }}" class="image-responsive" style="max-height:150px">
            {% endif %}
            <div class="caption post-detail-item">
                <h2>
                    <a href="">{{ obj.title }}</a>
                    <small>{{ obj.created_date | timesince }} ago</small>
                </h2>
                <h4><b> {% if obj.author.get_full_name %}
                            {{ obj.author.get_full_name }}
                        {% else %}
                            {{ obj.author }}
                        {% endif %}</b></h4>
                <p>{{ obj.get_markdown|truncatewords_html:1 }}</p>

                <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
                    <a href="{% url 'posts:edit' slug=obj.slug %}" class="btn btn-warning" role="button">Edit</a>
                    <a href="{% url 'posts:delete' slug=obj.slug %}" class="btn btn-danger" role="button">Delete</a></p>
            </div>
        </div>
    </div>
    {% cycle '' '<div class="col-sm-12"><hr></div></div><div class="row">' %}
    {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if objects.has_previous %}
            <a href="?page={{ objects.previous_page_number }}{% if request.GET.qry %}&qry={{request.GET.qry}}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ objects.number }} of {{ objects.paginator.num_pages }}.
        </span>

        {% if objects.has_next %}
            <a href="?page={{ objects.next_page_number }}{% if request.GET.qry %}&qry={{request.GET.qry}}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

</div>




{% endblock %}

blog/templates/blog/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

blog/templates/blog/postform.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %} Form {% endblock title%}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}

<div class="col-sm-offset-2 col-sm-8 col-sm-offset-2">
    <div class="col-sm-6">
        <h1>Preview</h1>
        <div class="content-preview">
            <h3 id="preview-title"></h3>
            <p id="preview-content"></p>
        </div>
    </div>

    <div class="col-sm-6">
    <h2>Form</h2>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form|crispy }}</p>
    <input type="submit" value="Create">
    </form>
    </div>
</div>

{% endblock content %}